#!/bin/sh

set -eu

if [ $# -ne 2 ]; then
    echo "fatal: invalid arguments" >&2
    exit 1
fi

host="$1"
port="$2"

openssl s_client -connect "$host:$port" < /dev/null 2>/dev/null | openssl x509 -fingerprint -sha256 -noout -in /dev/stdin
